In [1]:
import numpy as np

In [2]:
myList = [1,2,3]
np.array(myList)

array([1, 2, 3])

In [3]:
nested_list = [[1,2], [3, 4], [5,6]]

In [4]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,15))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [11]:
np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [12]:
np.linspace(0,100,7)

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

In [13]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [14]:
np.eye((5,5))

TypeError: 'tuple' object cannot be interpreted as an integer

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(4)

array([0.00340121, 0.95248554, 0.31877646, 0.62395244])

In [17]:
np.random.rand(3, 4)

array([[0.21803436, 0.93391787, 0.44785739, 0.98001935],
       [0.21820722, 0.12591778, 0.13588116, 0.26085941],
       [0.48811905, 0.81941829, 0.87357872, 0.2136417 ]])

In [18]:
np.random.randn(5)

array([-0.96749049, -0.65180125, -1.48249501, -0.9201928 , -1.84477176])

In [19]:
np.random.randn(5,5)

array([[ 0.19374216,  1.52152005,  0.3487077 , -1.31858167,  0.08881168],
       [-0.62792804, -0.31763634, -2.3918726 , -0.64799552,  0.61103578],
       [-0.85364122, -1.76029233,  0.52036232, -1.80868393,  0.59641546],
       [ 0.05110823,  0.05067612,  1.58097576,  2.15598463,  0.13230246],
       [-2.27915515,  0.96655311, -0.32911681, -0.25368016,  1.17331769]])

In [20]:
ar = np.random.randn(5,5)

In [21]:
ar

array([[ 0.11296915,  1.25835288,  0.88624269,  0.25647564, -1.33058738],
       [ 0.64778203,  0.40891674,  0.9301973 , -0.04554475,  0.240693  ],
       [-0.14714814, -0.95574547,  0.11727812, -0.00354562,  0.35606541],
       [-0.22110117, -0.32646645,  0.27015989,  1.42163186,  0.52840723],
       [-0.94942524,  0.59145236, -1.41612306,  0.88607503, -0.48286954]])

In [22]:
np.random.randint(1, 100)

51

In [23]:
np.random.randint(1, 100, 10)

array([50, 33, 79, 37, 67, 39, 55,  6, 12, 34])

In [24]:
np.random.seed(42)

In [25]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [26]:
arr = arange(25)

NameError: name 'arange' is not defined

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr = arr.reshape(5, 5)

In [30]:
arr.shape

(5, 5)

In [31]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.reshape(3,7)

ValueError: cannot reshape array of size 25 into shape (3,7)

In [33]:
ranarr = np.random.randint(0,50,10)

In [34]:
ranarr.max()

39

In [35]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [36]:
ranarr.argmax()

7

In [37]:
ranarr.min()

2

In [38]:
ranarr.argmin()

9

In [39]:
ranarr.dtype

dtype('int64')

In [40]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[8]

8

In [43]:
arr[1:4]

array([1, 2, 3])

In [44]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[0:5] = 100

In [47]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr = np.arange(0,11)

In [49]:
slice_of_arr = arr[0:5]

In [50]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [51]:
slice_of_arr[:] = 99

In [52]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [53]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [54]:
arr_copy = arr.copy()

In [55]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [56]:
arr_copy[0:5] = 100

In [57]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [58]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [59]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [60]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[0]

array([ 5, 10, 15])

In [62]:
arr_2d[0][1:3]

array([10, 15])

In [63]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [64]:
arr_2d[:2][1:]

array([[20, 25, 30]])

In [65]:
arr_2d[0:2][1:3]

array([[20, 25, 30]])

In [66]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [68]:
arr = np.arange(1, 11)

In [69]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
bool_arr = arr > 4

In [72]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr = arr[bool_arr]

In [75]:
arr

array([ 5,  6,  7,  8,  9, 10])

In [76]:
arr = np.arange(1, 11)

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
arr = np.arange(0, 10)

In [80]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
arr / 3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [82]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [83]:
arr / arr

/var/folders/vp/h9397tqn6373kx1nb5kddrz80000gn/T/ipykernel_68911/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [86]:
arr.sum()

45

In [87]:
arr.mean()

4.5

In [88]:
arr.std()

2.8722813232690143

In [89]:
arr.var()

8.25

In [90]:
np.arange(0,25,(5, 5))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [91]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [92]:
arr_2d = np.arange(0,25)

In [93]:
arr_2d.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [94]:
arr_2d.sum()

300

In [95]:
arr_2d.sum(axis=0)

300

In [96]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [97]:
arr_2d = arr_2d.reshape(5, 5)

In [98]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [99]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])